language: julia

julia:
  - 1.0
  - 1
os:
  - linux
  - osx
  - windows

notifications:
  email:
    - sunbergzach@gmail.com

# after_success:
# - julia --project -e 'import Pkg; Pkg.add("Documenter"); include("docs/make.jl")'
# - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
script:
  - git clone https://github.com/JuliaRegistries/General  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "General"))')
  - git clone https://github.com/JuliaPOMDP/Registry  $(julia -e 'import Pkg; println(joinpath(Pkg.depots1(), "registries", "JuliaPOMDP"))')
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("POMDPExamples"; coverage=true)'

after_success:
  - julia --project --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia --project --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
